### ISSUE TITLE
Running web-chat example fails: You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by nicholasraphael** [status-im/js-waku#325] opened 2021-11-02 23:49 UTC
This is a support request

## Problem
Trying to run the web-chat example

Failed to compile.

```
./node_modules/js-waku/build/module/lib/waku_light_push/index.js 18:16
Module parse failed: Unexpected token (18:16)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     this.libp2p = libp2p;
|
>     if (options?.pubSubTopic) {
|       this.pubSubTopic = options.pubSubTopic;
|     } else {
```

## Notes
js-waku: 0.13.1
MacOS, Firefox and Chrome

**Comment by D4nte** [comment] 2021-11-05 10:44
Dupe of https://github.com/status-im/js-waku/issues/165

**Closed by D4nte** 2021-11-05 10:44 UTC
